Repository os-net-config/os-net-config, pull requests merged in 2025-06, with the labels that each got.

#232 nmstate: skip verification of patch ports
  os_net_config/impl_nmstate.py
  os_net_config/tests/test_impl_nmstate.py
Labels: ci-gate

#227 nmstate: avoid cleanup of ovs, sriov and other config.yaml interfaces
  os_net_config/cli.py
  os_net_config/common.py
  os_net_config/impl_nmstate.py
Labels: Wallaby

#235 sriov: enable debug mode for sriov service
  os_net_config/utils.py
Labels: Wallaby

#237 nmstate: skip verification of patch ports
  os_net_config/impl_nmstate.py
  os_net_config/tests/test_impl_nmstate.py
Labels: Wallaby

#238 ovs: add ovs_extra option for interface and sriov_vf
  os_net_config/impl_ifcfg.py
  os_net_config/impl_nmstate.py
  os_net_config/objects.py
  os_net_config/schema.yaml
  os_net_config/tests/test_impl_ifcfg.py
  os_net_config/tests/test_impl_nmstate.py
Labels: ci-passed

#239 nmstate: handle ovs_extra for ovs bonds
  os_net_config/impl_nmstate.py
  os_net_config/tests/test_impl_nmstate.py
Labels: ci-passed
