Repository os-net-config/os-net-config, pull requests merged in 2025-09, with the labels that each got.

#287 ovs: add pci address of vf used as member of ovs_bond
  os_net_config/objects.py
  os_net_config/tests/test_objects.py
Labels: Wallaby

#272 nmstate: add helpers to get pci address of DPDK ports / bonds
  os_net_config/impl_nmstate.py
  os_net_config/tests/test_impl_nmstate.py
Labels: ci-passed

#292 dcb: remove redundant call to reset_dcb_map
  os_net_config/cli.py
Labels: ci-passed

#295 cli: schema validation is needed only for user input
  os_net_config/cli.py
Labels: ci-passed

#289 rm_config: apply the remove_config section of config YAML
  os_net_config/__init__.py
  os_net_config/cli.py
  os_net_config/objects.py
  os_net_config/tests/test_cli.py
Labels: ci-passed

#279 rm_config: identify if device is managed by ifcfg provider
  os_net_config/impl_ifcfg.py
Labels: ci-passed

#297 cli: log full traceback on configuration failure
  os_net_config/cli.py
Labels: ci-passed

#275 nmstate: keep_addr_on_down dispatcher script
  os_net_config/impl_nmstate.py
  os_net_config/tests/test_impl_nmstate.py
  os_net_config/utils.py
Labels: ci-passed

#300 nmstate: fix sysctl path for tests
  os_net_config/tests/test_impl_nmstate.py
  os_net_config/utils.py
Labels: ci-failed
